In [ ]:
%matplotlib inline

텐서(Tensor)
==========================================================================

텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조이다.
PyTorch에서는 모델의 **입력(input)**과 **출력(output)**, **중간 계산 결과**, 그리고 모델의 **매개변수**들을 텐서 타입의 객체로 저장한다.

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 `NumPy`의 `ndarray`와 유사하다. 실제로 텐서와 NumPy 배열(array)은 종종 동일한 내부 메모리를 공유할 수 있어 데이터를 복사할 필요가 없기도 하다.

텐서는 또한 자동 미분(automatic differentiation)에 최적화되어 있다. 자동 미분에 대해서는 나중에 따로 다룬다.

In [ ]:
import torch
import numpy as np

## 텐서(tensor)의 생성

### 데이터로부터 직접 생성하기

기본적인 형태의 신경망의 경우에 사용자가 직접 텐서를 생성할 필요는 별로 없다. 입력 텐서는 `DataLoader`에 의해서 자동으로 생성되고, 신경망의 패러매터들은 `torch.nn`이 제공하는 모듈내에 이미 포함되어 있기 때문이다. 다만 신경망의 출력 텐서를 최종적으로 배열이나 스칼라 값으로 변환하는 일은 해주어야 하는 경우가 있다. 

하지만 조금 복잡한 구조의 신경망을 구성할 경우 때때로 텐서를 직접 생성해주어야 할 수도 있다. 스칼라 데이터나 리스트로부터 직접 텐서를 생성할 수 있다. 이때 데이터의 자료형(data type)은 명시적으로 지정해 줄 수도 있고, 지정하지 않으면 자동으로 유추한다.

In [ ]:
#길이가 2인 2개의 하위 목록을 포함하는 2D python 목록 data 생성
data = [[1, 2],[3, 4]]
#torch.tensor 사용하여 pytorch 텐서 x_data로 변환
x_data = torch.tensor(data)
x_data
#결과 텐서는 (2,2)차원 가지며 원래 목록 데이터와 동일한 값을 포함

tensor([[1, 2],
        [3, 4]])

### NumPy 배열로부터 생성하기

텐서는 NumPy 배열로부터 생성할 수 있다. 그 반대도 가능하다.



In [ ]:
#numpy배열 생성
np_array = np.array(data)
# from_numpy 메서드로 Tensor를 생성
x_np = torch.from_numpy(np_array)
print(x_np)
#dtype 속성 사용하여 tensor x-np와 데이터 유형 인쇄 
print(x_np.dtype)
#torch 모듈의 tensor생성자를 사용하여 x_np2라는 또 다른 텐서 생성 인수는 float으로 지정
x_np2 = torch.tensor(np_array, dtype=float) # torch.tensor 생성자로 Tensor를 생성할 수도 있음. dtype을 지정 가능

print(x_np2)
#dtype 속성하용하여 tensor x_np2와 데이터 유형 인쇄
print(x_np2.dtype)

# 배열의 값을 수정한다.
np_array[0, 0] = 0    
# from_numpy로 생성한 경우 배열의 데이터를 공유한다.
print(x_np)     
# tensor 생성자로 생성한 경우 배열의 데이터를 공유하지 않는다.
print(x_np2)    

tensor([[1, 2],
        [3, 4]])
torch.int64
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.float64
tensor([[0, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


### 모양(shape)을 지정하여 텐서 생성하기

``shape`` 은 텐서의 모양을 나타내는 튜플(tuple)로, 아래 함수들에 출력 텐서의 모양을 결정한다.

In [ ]:
shape = (2,3)
# 0~1 사이의 랜덤 실수
rand_tensor = torch.rand(shape)   
#1로 채워진 텐서  
ones_tensor = torch.ones(shape)
#0으로 채워진 텐서
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor}\n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2870, 0.4751, 0.5503],
        [0.2546, 0.8531, 0.5603]])

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 다른 텐서로부터 생성하기

명시적으로 새로 정의하지 않는다면, 인자로 주어진 텐서의 속성(`shape`, `dtype`)을 유지한다.

In [ ]:
# x_data의 속성을 유지합니다.
x_ones = torch.ones_like(x_data)   
print(x_ones)

# x_data의 속성을 유지합니다.
x_zeros = torch.zeros_like(x_data) 
print(x_zeros)

# x_data의 속성을 덮어씁니다.
x_rand = torch.rand_like(x_data, dtype=torch.float) 
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0, 0],
        [0, 0]])
tensor([[0.4350, 0.5442],
        [0.3019, 0.4912]])


--------------

## 텐서의 기본 속성(attributes)

모든 텐서는 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지 등의 속성을 가진다.

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**참고:** 지난 시간의 `PyTorch_Quickstart` 강좌에서 다룬 입력과 출력 데이터들의 타입과 `shape`, `dtype`등의 속성을 확인해보자.

--------------

## 텐서 연산(Operation)

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수 연산,
랜덤 샘플링(random sampling) 등 다양한 텐서 연산들을
[여기](<https://pytorch.org/docs/stable/torch.html>)에서 확인할 수 있다. 목록에서 몇몇 연산들을 시도해보라.
NumPy API에 익숙하다면 Tensor API를 사용하는 것은 쉽다는 것을 알게 될 것이다.

각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수도 있다. Colab을 사용한다면, `Edit > Notebook Settings` 에서 GPU를 할당할 수 있다.

기본적으로 텐서는 CPU에 생성된다. ``.to`` 메소드를 사용하면 GPU로 텐서를 명시적으로 이동할 수 있다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하라!

In [ ]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

#### **NumPy 방식의 인덱싱과 슬라이싱:**



In [ ]:
tensor = torch.tensor([[1,2,3,4],
                       [5,6,7,8],
                       [9,10,11,12],
                       [13,14,15,16]
                       ])
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")    # ...은 앞쪽의 모든 차원에 대해서 "모든 범위"임을 의미한다. 3차원 이상의 다차원 배열을 다룰 때 유용한 표현이다.
tensor[:,1] = 0
print(tensor)

First row: tensor([1, 2, 3, 4])
First column: tensor([ 1,  5,  9, 13])
Last column: tensor([ 4,  8, 12, 16])
tensor([[ 1,  0,  3,  4],
        [ 5,  0,  7,  8],
        [ 9,  0, 11, 12],
        [13,  0, 15, 16]])


#### **텐서 합치기:** 

``torch.cat``을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다.

In [ ]:
tensor = torch.tensor([[1,2,3,4],
                       [5,6,7,8],
                       [9,10,11,12]])
#torch.cat 함수는 행과 열을 따라 텐서를 자신과 연결하는데 사용
t0 = torch.cat([tensor, tensor])
print(t0)
t1 = torch.cat([tensor, tensor], dim=1)  # dim을 지정하여 어떤 축으로 연결할지 지정한다.
print(t1)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12]])


`torch.cat`과는 달리 `torch.stack`은 새로운 차원을 추가하여 텐서를 합친다.

In [ ]:
t2 = torch.stack([tensor, tensor])
print(t2.shape)
print(t2)

torch.Size([2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])


위의 예에서 보듯 새로 추가된 차원이 첫 번째 축(axis)이 된다. `axis` 인자를 통해서 새로 추가된 차원이 몇 번째 축이 될지 지정할 수도 있다.

In [ ]:
t3 = torch.stack([tensor, tensor], axis=1)
print(t3.shape)
print(t3)

torch.Size([3, 2, 4])
tensor([[[ 1,  2,  3,  4],
         [ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [ 9, 10, 11, 12]]])


#### **텐서 모양 변경하기(reshape):** 

원소의 개수가 유지되는 경우 텐서의 차원의 개수와 모양을 자유롭게 변경할 수 있다.

In [ ]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a = torch.reshape(a, (1, 3, 4))
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

원소의 개수는 불변이므로 크기가 유추 가능한 경우 -1로 표시할 수 있다.

In [ ]:
b = torch.reshape(a, (-1, 2, 3))
print(b)
print(b.shape)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([2, 2, 3])


`squeeze` 메서드로 크기가 1인 차원을 제거하거나, `unsqueez` 메서드로 차원을 추가할 수 있다.

In [ ]:
x = torch.rand(1, 1, 20, 128)
x = x.squeeze() # [1, 1, 20, 128] -> [20, 128]
print(x.shape)

x2 = torch.rand(1, 1, 20, 128)
x2 = x2.squeeze(dim=1) # [1, 1, 20, 128] -> [1, 20, 128]
print(x2.shape)

torch.Size([20, 128])
torch.Size([1, 20, 128])


In [ ]:
x = torch.rand([2, 3])
x1 = torch.unsqueeze(x, 0)
x1.shape

torch.Size([1, 2, 3])

이외에도 텐서의 모양을 변경하는 방법으로는 [`flatten`](https://pytorch.org/docs/stable/generated/torch.flatten.html), [`view`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html), [`expand`](https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html), `None` indexing 등이 있다.

#### **산술 연산(Arithmetic operations)**



 텐서와 스칼라간의 기본적인 산술 연산을 지원한다.

In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [ ]:
fives = ones + fours
print(fives)

# 요소별 곱(element-wise product)을 계산한다. dozens1, dozens2는 같은 값을 갖는다.
dozens1 = threes * fours
dozens2 = threes.mul(fours)
print(dozens1)
print(dozens2)

tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])
tensor([[12., 12.],
        [12., 12.]])


행렬곱은 `@` 연산자 혹은 `matmul` 메서드로 지원한다.

In [ ]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산한니다. y1, y2는 같은 값을 갖는다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)

tensor([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])
tensor([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])


#### Broadcasting

Broadcasting은 서로 다른 shape을 가진 텐서끼리 산술연산을 지원하는 기법을 의미한다. 예를 들어보자.

In [ ]:
A = torch.rand(2, 4)  
B = torch.ones(1, 4) * 2
print(A)
print(B)
C = A + B
print(C)
D = A * B
print(D)

tensor([[0.4544, 0.5118, 0.6063, 0.4226],
        [0.8554, 0.9073, 0.6393, 0.5394]])
tensor([[2., 2., 2., 2.]])
tensor([[2.4544, 2.5118, 2.6063, 2.4226],
        [2.8554, 2.9073, 2.6393, 2.5394]])
tensor([[0.9088, 1.0236, 1.2126, 0.8451],
        [1.7108, 1.8147, 1.2786, 1.0788]])


 Broadcasting에 관한 세부규칙은 Numpy와 동일하다.

#### 기타 산술연산

텐서는 이외에도 매우 다양한 산술연산을 제공한다.

In [ ]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print(a)
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))  # 올림 연산
print(torch.floor(a)) # 내림 연산
print(torch.clamp(a, -0.5, 0.5)) # -0.5 이하는 -0.5로, 0.5 이상은 0.5로 변환

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.min(d))        # returns a single-element tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers

tensor([[ 0.9577, -0.3478,  0.8367, -0.7660],
        [-0.2441, -0.2934,  0.6736,  0.3762]])
Common functions:
tensor([[0.9577, 0.3478, 0.8367, 0.7660],
        [0.2441, 0.2934, 0.6736, 0.3762]])
tensor([[1., -0., 1., -0.],
        [-0., -0., 1., 1.]])
tensor([[ 0., -1.,  0., -1.],
        [-1., -1.,  0.,  0.]])
tensor([[ 0.5000, -0.3478,  0.5000, -0.5000],
        [-0.2441, -0.2934,  0.5000,  0.3762]])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
tensor(1.)
tensor(2.5000)
tensor(1.2910)
tensor(24.)


#### **단일-요소(single-element) 텐서:** 

단일 스칼라 값을 저장하는 텐서의 경우, ``item()``을 사용하여 숫자 값으로 변환할 수 있다:



In [ ]:
agg = tensor.sum()   # 1 + 2 + ... + 12 = 78
agg_item = agg.item()
print(agg_item, type(agg_item))

78 <class 'int'>


#### **바꿔치기(in-place) 연산:**

연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, ``_`` 접미사를 갖는다.
예를 들어: ``x.copy_(y)`` 나 ``x.t_()`` 는 ``x`` 를 변경한다.



In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

**Note:** 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있다. 따라서, 사용을 권장하지 않는다.



--------------




## NumPy 변환(Bridge)

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.



#### **텐서를 NumPy 배열로 변환하기**


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영된다.



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


#### **NumPy 배열을 텐서로 변환하기**

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영된다.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
